;;; stem-english-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stem-english.el

(autoload 'stem-english "stem-english" "\


(fn STR)")
(register-definition-prefixes "stem-english" '("stem-english-"))

;;; End of scraped data

(provide 'stem-english-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stem-english-autoloads.el ends here
