;;; xmind-org-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from xmind-org.el

(autoload 'xmind-org-insert-file "xmind-org" "\
Insert an XMind FILE into the current Org buffer.

(fn FILE)" t)
(register-definition-prefixes "xmind-org" '("xmind-org-"))

;;; End of scraped data

(provide 'xmind-org-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xmind-org-autoloads.el ends here
